name: vagas_design_system
description: A Design System Package to App Vagas Elite37.
version: 0.0.1

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  auto_size_text: ^3.0.0
  flutter_svg: 1.1.6
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/assets/
    - lib/assets/images/
